// Comprehensive list of AWS SDK v3 JavaScript client packages
// This list includes the most commonly used AWS services
// For a complete list, see: https://github.com/aws/aws-sdk-js-v3/tree/main/clients

export const AWS_SERVICES = [
	"@aws-sdk/client-s3",
	"@aws-sdk/client-dynamodb",
	"@aws-sdk/client-ec2",
	"@aws-sdk/client-lambda",
	"@aws-sdk/client-iam",
	"@aws-sdk/client-cloudformation",
	"@aws-sdk/client-cloudwatch",
	"@aws-sdk/client-cloudwatch-logs",
	"@aws-sdk/client-sns",
	"@aws-sdk/client-sqs",
	"@aws-sdk/client-rds",
	"@aws-sdk/client-ecs",
	"@aws-sdk/client-eks",
	"@aws-sdk/client-elasticache",
	"@aws-sdk/client-elastic-load-balancing-v2",
	"@aws-sdk/client-route-53",
	"@aws-sdk/client-api-gateway",
	"@aws-sdk/client-apigatewayv2",
	"@aws-sdk/client-cognito-identity",
	"@aws-sdk/client-cognito-identity-provider",
	"@aws-sdk/client-secrets-manager",
	"@aws-sdk/client-ssm",
	"@aws-sdk/client-kms",
	"@aws-sdk/client-cloudfront",
	"@aws-sdk/client-eventbridge",
	"@aws-sdk/client-step-functions",
	"@aws-sdk/client-kinesis",
	"@aws-sdk/client-firehose",
	"@aws-sdk/client-athena",
	"@aws-sdk/client-glue",
	"@aws-sdk/client-redshift",
	"@aws-sdk/client-sagemaker",
	"@aws-sdk/client-bedrock",
	"@aws-sdk/client-bedrock-runtime",
	"@aws-sdk/client-sts",
	"@aws-sdk/client-organizations",
	"@aws-sdk/client-cloudtrail",
	"@aws-sdk/client-config-service",
	"@aws-sdk/client-guardduty",
	"@aws-sdk/client-inspector2",
	"@aws-sdk/client-securityhub",
	"@aws-sdk/client-waf",
	"@aws-sdk/client-wafv2",
	"@aws-sdk/client-shield",
	"@aws-sdk/client-acm",
	"@aws-sdk/client-certificate-manager",
	"@aws-sdk/client-elastic-beanstalk",
	"@aws-sdk/client-amplify",
	"@aws-sdk/client-appsync",
	"@aws-sdk/client-batch",
	"@aws-sdk/client-codecommit",
	"@aws-sdk/client-codebuild",
	"@aws-sdk/client-codedeploy",
	"@aws-sdk/client-codepipeline",
	"@aws-sdk/client-codeartifact",
	"@aws-sdk/client-ecr",
	"@aws-sdk/client-efs",
	"@aws-sdk/client-fsx",
	"@aws-sdk/client-backup",
	"@aws-sdk/client-glacier",
	"@aws-sdk/client-storage-gateway",
	"@aws-sdk/client-transfer",
	"@aws-sdk/client-datasync",
	"@aws-sdk/client-dms",
	"@aws-sdk/client-application-auto-scaling",
	"@aws-sdk/client-auto-scaling",
	"@aws-sdk/client-elastic-load-balancing",
	"@aws-sdk/client-vpc-lattice",
	"@aws-sdk/client-app-mesh",
	"@aws-sdk/client-cloud-map",
	"@aws-sdk/client-service-discovery",
	"@aws-sdk/client-xray",
	"@aws-sdk/client-cloudwatch-events",
	"@aws-sdk/client-scheduler",
	"@aws-sdk/client-pipes",
	"@aws-sdk/client-mq",
	"@aws-sdk/client-kafka",
	"@aws-sdk/client-kinesis-analytics",
	"@aws-sdk/client-kinesis-video",
	"@aws-sdk/client-mediaconvert",
	"@aws-sdk/client-medialive",
	"@aws-sdk/client-mediapackage",
	"@aws-sdk/client-mediastore",
	"@aws-sdk/client-transcribe",
	"@aws-sdk/client-translate",
	"@aws-sdk/client-polly",
	"@aws-sdk/client-rekognition",
	"@aws-sdk/client-textract",
	"@aws-sdk/client-comprehend",
	"@aws-sdk/client-lex-runtime-service",
	"@aws-sdk/client-lex-models-v2",
	"@aws-sdk/client-personalize",
	"@aws-sdk/client-forecast",
	"@aws-sdk/client-lookout-for-vision",
	"@aws-sdk/client-iot",
	"@aws-sdk/client-iot-data-plane",
	"@aws-sdk/client-iot-events",
	"@aws-sdk/client-iot-analytics",
	"@aws-sdk/client-greengrass",
	"@aws-sdk/client-timestream-write",
	"@aws-sdk/client-timestream-query",
	"@aws-sdk/client-neptune",
	"@aws-sdk/client-docdb",
	"@aws-sdk/client-elasticache",
	"@aws-sdk/client-memorydb",
	"@aws-sdk/client-keyspaces",
	"@aws-sdk/client-qldb",
	"@aws-sdk/client-cloudsearch",
	"@aws-sdk/client-elasticsearch-service",
	"@aws-sdk/client-opensearch",
	"@aws-sdk/client-emr",
	"@aws-sdk/client-emr-serverless",
	"@aws-sdk/client-mwaa",
	"@aws-sdk/client-databrew",
	"@aws-sdk/client-quicksight",
	"@aws-sdk/client-cost-explorer",
	"@aws-sdk/client-budgets",
	"@aws-sdk/client-pricing",
	"@aws-sdk/client-marketplace-catalog",
	"@aws-sdk/client-license-manager",
	"@aws-sdk/client-service-catalog",
	"@aws-sdk/client-resource-groups",
	"@aws-sdk/client-resource-groups-tagging-api",
	"@aws-sdk/client-ram",
	"@aws-sdk/client-workspaces",
	"@aws-sdk/client-appstream",
	"@aws-sdk/client-workdocs",
	"@aws-sdk/client-chime",
	"@aws-sdk/client-connect",
	"@aws-sdk/client-pinpoint",
	"@aws-sdk/client-ses",
	"@aws-sdk/client-sesv2",
	"@aws-sdk/client-device-farm",
	"@aws-sdk/client-mobile",
	"@aws-sdk/client-gamelift",
	"@aws-sdk/client-robomaker",
	"@aws-sdk/client-ground-station",
	"@aws-sdk/client-braket",
	"@aws-sdk/client-honeycode",
	"@aws-sdk/client-location",
	"@aws-sdk/client-nimble",
	"@aws-sdk/client-proton",
	"@aws-sdk/client-wisdom",
	"@aws-sdk/client-voice-id",
	"@aws-sdk/client-panorama",
	"@aws-sdk/client-cloudcontrol",
	"@aws-sdk/client-account",
	"@aws-sdk/client-amp",
	"@aws-sdk/client-grafana",
	"@aws-sdk/client-prometheus",
	"@aws-sdk/client-rum",
	"@aws-sdk/client-evidently",
	"@aws-sdk/client-fis",
	"@aws-sdk/client-resiliencehub",
	"@aws-sdk/client-migration-hub",
	"@aws-sdk/client-application-discovery-service",
	"@aws-sdk/client-mgn",
	"@aws-sdk/client-sms",
	"@aws-sdk/client-snow-device-management",
	"@aws-sdk/client-snowball",
	"@aws-sdk/client-direct-connect",
	"@aws-sdk/client-global-accelerator",
	"@aws-sdk/client-network-firewall",
	"@aws-sdk/client-network-manager",
	"@aws-sdk/client-private-networks",
	"@aws-sdk/client-vpc",
	"@aws-sdk/client-lightsail",
	"@aws-sdk/client-outposts",
	"@aws-sdk/client-compute-optimizer",
	"@aws-sdk/client-wellarchitected",
	"@aws-sdk/client-controltower",
	"@aws-sdk/client-sso",
	"@aws-sdk/client-sso-admin",
	"@aws-sdk/client-identitystore",
	"@aws-sdk/client-directory-service",
	"@aws-sdk/client-access-analyzer",
	"@aws-sdk/client-audit-manager",
	"@aws-sdk/client-detective",
	"@aws-sdk/client-macie2",
	"@aws-sdk/client-fms",
	"@aws-sdk/client-health",
	"@aws-sdk/client-support",
	"@aws-sdk/client-trustedadvisor",
	"@aws-sdk/client-service-quotas",
	"@aws-sdk/client-pi",
	"@aws-sdk/client-application-insights",
	"@aws-sdk/client-synthetics",
	"@aws-sdk/client-osis",
	"@aws-sdk/client-oam",
	"@aws-sdk/client-internetmonitor",
	"@aws-sdk/client-cloudwatch-network-monitor",
];

/**
 * Validates if a service package name is in the known list
 * @param {string} service - The service package name (e.g., "@aws-sdk/client-s3")
 * @returns {boolean} - True if valid, false otherwise
 */
export function isValidService(service) {
	return AWS_SERVICES.includes(service);
}

/**
 * Gets service name suggestions based on partial input
 * @param {string} input - Partial service name
 * @returns {string[]} - Array of matching service names
 */
export function getServiceSuggestions(input) {
	if (!input) return AWS_SERVICES;
	
	const lowerInput = input.toLowerCase();
	return AWS_SERVICES.filter(service => 
		service.toLowerCase().includes(lowerInput)
	);
}

/**
 * Extracts the service display name from package name
 * @param {string} packageName - Full package name (e.g., "@aws-sdk/client-s3")
 * @returns {string} - Display name (e.g., "S3")
 */
export function getServiceDisplayName(packageName) {
	return packageName
		.replace("@aws-sdk/client-", "")
		.split("-")
		.map(word => word.toUpperCase())
		.join(" ");
}
